spring:
  application:
    name: github
  config:
    import:
    - optional:file:.env[.properties]
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    url: ${DB_URL}
    password: ${DB_PW}
  data:
    redis:
      host: redis
      port: 6379
github:
  api:
    url: https://api.github.com
    token: ${GITHUB_TOKEN}
mybatis:
  mapper-locations:
  - classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true